/**
 * Generates CSS custom properties from the TS token source (semantic.ts).
 * TS stays the single source of truth; CSS output is derived, never hand-edited.
 * Run via `pnpm --filter @filmset/tokens build`.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  controlHeight,
  motion,
  opacity,
  panelWidth,
  radius,
  shadow,
  spacing,
  tableRow,
  themes,
  typography,
  zIndex,
  type ThemeName,
} from "../src/index";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "dist", "css");
mkdirSync(outDir, { recursive: true });

const HEADER = `/* Generated by packages/tokens/scripts/build-css.ts — do not hand-edit. */\n`;

function kebab(input: string): string {
  return input.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function colorVarBlock(theme: ReturnType<typeof colorEntries>): string {
  return theme.map(([name, value]) => `  --fs-color-${name}: ${value};`).join("\n");
}

function colorEntries(themeName: ThemeName): [string, string][] {
  const c = themes[themeName];
  const entries: [string, string][] = [];
  for (const [group, values] of Object.entries(c)) {
    for (const [key, value] of Object.entries(values as Record<string, string>)) {
      entries.push([`${kebab(group)}-${kebab(key)}`, value]);
    }
  }
  return entries;
}

// --- Theme-independent tokens: spacing, radius, typography, motion, shadow, opacity, control height, panel widths, z-index ---
const baseLines: string[] = [":root {"];

for (const [key, value] of Object.entries(spacing)) {
  baseLines.push(`  --fs-space-${key}: ${value};`);
}
for (const [key, value] of Object.entries(radius)) {
  baseLines.push(`  --fs-radius-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(shadow)) {
  baseLines.push(`  --fs-shadow-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(opacity)) {
  baseLines.push(`  --fs-opacity-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(motion.duration)) {
  baseLines.push(`  --fs-motion-duration-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(motion.easing)) {
  baseLines.push(`  --fs-motion-easing-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(controlHeight)) {
  baseLines.push(`  --fs-control-height-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(tableRow)) {
  baseLines.push(`  --fs-table-row-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(panelWidth)) {
  baseLines.push(`  --fs-panel-${kebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(zIndex)) {
  baseLines.push(`  --fs-z-${kebab(key)}: ${value};`);
}
baseLines.push(`  --fs-font-family-ui: ${typography.fontFamily.ui};`);
baseLines.push(`  --fs-font-family-mono: ${typography.fontFamily.mono};`);
for (const [key, value] of Object.entries(typography.weight)) {
  baseLines.push(`  --fs-font-weight-${kebab(key)}: ${value};`);
}
for (const [role, def] of Object.entries(typography.role)) {
  const r = kebab(role);
  baseLines.push(`  --fs-type-${r}-size: ${def.size};`);
  baseLines.push(`  --fs-type-${r}-line-height: ${def.lineHeight};`);
  baseLines.push(`  --fs-type-${r}-weight: ${def.weight};`);
}
baseLines.push("}");

// Density resolves to a single active variable per component so nothing forks
// per density (§15) — components read --fs-control-height / --fs-table-row-height.
const densityLines = [
  ':root, [data-density="comfortable"] {',
  `  --fs-control-height: var(--fs-control-height-comfortable);`,
  `  --fs-table-row-height: var(--fs-table-row-comfortable);`,
  "}",
  '[data-density="compact"] {',
  `  --fs-control-height: var(--fs-control-height-compact);`,
  `  --fs-table-row-height: var(--fs-table-row-compact);`,
  "}",
];

writeFileSync(
  join(outDir, "tokens.css"),
  HEADER + baseLines.join("\n") + "\n\n" + densityLines.join("\n") + "\n",
  "utf8",
);

// --- Per-theme color variables ---
// light is the default (:root); dark and high-contrast activate via [data-theme].
const lightCss = `${HEADER}:root,\n[data-theme="light"] {\n${colorVarBlock(colorEntries("light"))}\n}\n`;
writeFileSync(join(outDir, "theme-light.css"), lightCss, "utf8");

const darkCss = `${HEADER}[data-theme="dark"] {\n${colorVarBlock(colorEntries("dark"))}\n}\n`;
writeFileSync(join(outDir, "theme-dark.css"), darkCss, "utf8");

const hcCss = `${HEADER}[data-theme="high-contrast"] {\n${colorVarBlock(colorEntries("high-contrast"))}\n}\n`;
writeFileSync(join(outDir, "theme-high-contrast.css"), hcCss, "utf8");

// --- Tailwind v4 @theme block: maps utility classes 1:1 to semantic token names ---
// e.g. bg-canvas -> var(--fs-color-background-canvas); text-primary -> var(--fs-color-text-primary)
const twLines: string[] = ["@theme inline {"];
const colorNames = colorEntries("light").map(([name]) => name);
for (const name of colorNames) {
  twLines.push(`  --color-${name}: var(--fs-color-${name});`);
}
for (const key of Object.keys(spacing)) {
  twLines.push(`  --spacing-${key}: var(--fs-space-${key});`);
}
for (const key of Object.keys(radius)) {
  twLines.push(`  --radius-${kebab(key)}: var(--fs-radius-${kebab(key)});`);
}
for (const key of Object.keys(shadow)) {
  twLines.push(`  --shadow-${kebab(key)}: var(--fs-shadow-${kebab(key)});`);
}
twLines.push(`  --font-ui: var(--fs-font-family-ui);`);
twLines.push(`  --font-mono: var(--fs-font-family-mono);`);
twLines.push("}");
writeFileSync(join(outDir, "tailwind-theme.css"), HEADER + twLines.join("\n") + "\n", "utf8");

console.log("[@filmset/tokens] CSS generated in dist/css/");
